### ISSUE TITLE
simpler Pool (bonus)

### ISSUE THREAD

**Issue by starsuit** [fac-17/Week-6-BHKM-#36]
https://github.com/fac-17/Week-6-BHKM-/blob/9de7ac8719b5f22d06532b65ccf313f24237a8f9/src/database/db_connection.js#L16

fun fact you don't actually need the `options` object - all of the data is already stored in your database url:
```
let connectionString = process.env.DATABASE_URL;
// this variable must be called 'connectionString' for this to work
module.exports = new Pool({
  connectionString,
  ssl: !connectionString.includes("localhost")
})
```

**Comment by xIrusux** [comment]
Done thanks!!
